version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: gradle integrationTest
      - store_test_results:
          path: reports/tests/integrationTest
      - store_artifacts:
          path: reports/tests/integrationTest

      - run: ./service.sh dev_build

  uat:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: echo "Hello World from UAT"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - uat:
          requires:
            - build