version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run: gradle test integrationTest

      - store_test_results:
          path: build/reports/tests
      - store_artifacts:
          path: build/reports/tests
          destination: results

      - run: ./service.sh dev_build

  uat:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Apply Offers DB migrations
          command: |
              export OFFERS_ENGINE_DB_URL="$UAT_OFFERS_ENGINE_DB_URL"
              export OFFERS_ENGINE_DB_USER="$UAT_OFFERS_ENGINE_DB_USER"
              export OFFERS_ENGINE_DB_PASSWORD="$UAT_OFFERS_ENGINE_DB_PASSWORD"

              cd db-scripts
              gradle liquibaseCreate liquibaseUpdate -DuserName=$UAT_OFFERS_ENGINE_DB_USER -Dpassword=$UAT_OFFERS_ENGINE_DB_PASSWORD -Durl=jdbc:postgresql://$OFFERS_ENGINE_DB_URL/offers_engine
              cd ../

      - run: echo "Hello World from UAT"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - uat:
          requires:
            - build