package com.ovoenergy.offer.validation.key;

public interface CodeKeys {

    String GENERIC_SERVER_ERROR = "OFR1";

    String FIELD_REQUIRED = "OFR2";

    String NOT_NULL_FIELD = "OFR3";

    String PROVIDED_VALUE_NOT_SUPPORTED = "OFR4";

    String INPUT_VALUE_ZERO = "OFR5";

    String NOT_UNIQUE_OFFER_CODE = "OFR6";

    String INVALID_OFFER_CODE = "OFR7";

    String NON_IN_FUTURE_DATE = "OFR8";

    String OFFER_EXPIRY_DATE_BEFORE_START_DATE = "OFR9";

    String NO_EXPIRY_OFFER_COULD_NOT_HAVE_EXPIRY_DATE = "OFR10";

    String INPUT_REDEMPTION_MAX = "OFR11";

    String INPUT_VALUE_MAX = "OFR12";

    String INVALID_EMAIL = "OFR13";

    String OFFER_INVALID = "OFR14";

    String OFFER_EXPIRED = "OFR15";

    String OFFER_STATUS_TYPE_NOT_VALID = "OFR16";

    String NULL_FIELD = "OFR17";

    String OFFER_CODE_FIELD_SIZE = "OFR18";

    String OFFER_NAME_FIELD_SIZE = "OFR19";

    String OFFER_DESCRIPTION_FIELD_SIZE = "OFR20";

    String PROVIDED_TWO_DIFFERENT_IDS = "OFR21";

    String ENTITY_NOT_EXIST = "OFR22";

    String START_DATE_NOT_UPDATABLE = "OFR23";

    String OFFER_LINK_EXPIRED = "OFR24";

    String INVALID_DATA_FORMAT = "OFR25";

}
